apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: default
data:
  redis.conf: |
    # Redis configuration file example
    # Add your Redis configuration here
    # ...
    appendonly yes

